Tutorial
deutsche-nationalbibliothek/pica-rs pull request #327
Opened 2021-11-10 16:30 UTC by a-wendler

v1 des Anfänger-Tutorials auf Deutsch inkl. Testdaten.

2021-11-19 11:06 UTC, niko2342 requested changes
Lieber André,

vielen Dank für das tolle Tutorial. Ich habe noch ein paar Anmerkungen hinzugefügt. Die neuen Features, die jetzt reingekommen sind, würde ich dann im Nachgang dokumentieren.

2021-11-19 11:06 UTC, niko2342 commented on docs/book/src/de/beginner-tutorial.md
> +## Warum zwei Filtermöglichkeiten?
Der erste Filter arbeitet auf Datensatz-Ebene; der Filter im Select-Kommando aber der Feld-Ebene. Die Dopplungen lassen sich leider nicht umgehen.

2021-11-19 11:06 UTC, niko2342 commented on docs/book/src/de/beginner-tutorial.md
> +- slice
Ich würde slice und split nicht in das Beginner-Tutorial aufnehmen. Es wird noch für jedes Kommando eine sehr detaillierte Beschreibung folgen.

2021-11-19 13:39 UTC, a-wendler commented
danke, @niko2342 für die Kommentare. Noch einmal für mich als GitHub-Newbie: ich setze jetzt die von Dir angeregte Änderungen um und dann?

2021-11-19 14:04 UTC, a-wendler commented on docs/book/src/de/beginner-tutorial.md
> +Zum Testen steht unter [https://github.com/a-wendler/pica-rs/blob/tutorial/docs/book/src/de/testdaten.dat](https://github.com/a-wendler/pica-rs/blob/tutorial/docs/book/src/de/testdaten.dat) ein Testd
danke für die aufmerksamkeit. das war nicht gewollt. ändere ich.

2021-11-19 14:06 UTC, niko2342 commented
@a-wendler Dann schaue ich nochmal drüber und merge die Änderung in das Repo.

2021-11-22 07:01 UTC, niko2342 approved these changes

2021-11-22 07:01 UTC, merged