add tutorial for rmarkdown with pica
deutsche-nationalbibliothek/pica-rs pull request #351
Opened 2021-11-29 15:57 UTC by mfakaehler

I have added a tutorial that uses pica-rs in conjuction with R in a rmarkdown file. **Note, that the .md-file is automatically generated by the r-package knitr.** Any editing shoul be in the source-rmd rather then the .md-file. Before merging this into main, we need to figure out, which of the files need to be included:

- Do we need the original source-.rmd that generates the intermediate .md-file?
- Do we need to include an output html-file that a user would normally generate with pandoc from the attached rmd-file/ md-file?
- Do we include other files that are generated by knitr, for example the figures?

2021-11-29 19:51 UTC, niko2342 commented
@mfakaehler Thx for your contribution!

> * Do we need the original source-.rmd that generates the intermediate .md-file?

No.

> * Do we need to include an output html-file that a user would normally generate with pandoc from the attached rmd-file/ md-file?

No.

> * Do we include other files that are generated by knitr, for example the figures?

The figures are very useful to illustrate what is possible with R (Markdown).

I'm going to do a detailed review tomorrow.

2021-11-30 08:17 UTC, niko2342 requested changes
Lieber Max,

vielen Dank für das Tutorial. Ich habe noch ein paar Anmerkungen; danach kann der PR in den main-Branch.

BG
Nico

2021-11-30 08:17 UTC, niko2342 commented on docs/book/src/de/using-pica-rs-with-rmarkdown/using-pica-rs-with-rmarkdown.md
> +```r
```r
title_idn_gnd_idn <- read_csv("title_idn_gnd_idn.csv", 
    col_types = list(idn_titel = col_factor(), idn_sw = col_factor()))
```

2021-11-30 08:17 UTC, niko2342 commented on docs/book/src/de/using-pica-rs-with-rmarkdown/using-pica-rs-with-rmarkdown.md
> +In dem so erzeugten Datensatz gibt es 245 verschiedene GND-Terme,
Könntest du bitte im gesamten Tutorial "GND-Term" durch "GND-Entität" ersetzen.

2021-11-30 10:10 UTC, mfakaehler commented
Ich bin jetzt durch mit meinen Korrekturen.

2021-11-30 11:24 UTC, merged