Include JSON in README list of commands
deutsche-nationalbibliothek/pica-rs pull request #364
Opened 2021-12-07 11:30 UTC by nichtich

Marked as unstable because of
<https://github.com/deutsche-nationalbibliothek/pica-rs/issues/249>.

2021-12-08 09:57 UTC, niko2342 commented
I've removed the `json` command in this table, because I'm not sure how to proceed with this command. On the one hand, this command causes irritation, because of the format. The picadata eco-system uses the so called [PICA JSON](http://format.gbv.de/pica/json) format, which is compact, but not readable. (I do not like this format). Also the IT department of the DNB is not happy, because they use different identifier ("name" instead of "tag", etc).

On the other hand, it serializes the internal data structure very efficient with a low memory footprint. This is very useful when serializing more than 100.000 records. Furthermore, it is very useful to have a descriptive format when deserialize json data in python (use strings in a dictionary).

In my opinion there shouldn't be a discussion about the "right" way to serialize PICA+ data in json. There are different requirements which lead to different json serializations. If we can all agree on this, I'll add the command in the README (and documentation) back. Otherwise this command gets a hidden feature, which must be enabled explicitly.

Notwithstanding the above, the `json` command is not unstable.

2021-12-08 10:24 UTC, nichtich commented
If it has a use case, it should be documented. I only ask for a name to list and describe it at http://format.gbv.de/pica. and not to change the format once it has been established.

2021-12-15 07:53 UTC, niko2342 requested changes

2021-12-15 07:53 UTC, niko2342 commented on README.md
> +| [json](#json)           | unstable  | serialize records in JSON                                         |
Stability of the command is beta

2021-12-15 07:53 UTC, niko2342 commented on README.md
> +To serialize a record to JSON, just run the following command:
I think the description should be clear about the resulting format. I propose sth. like this: This command serialize the internal representation of a record to JSON. The resulting JSON can be used to do subsequent data analysis (ex. in Python), but should not be used as an interchange format (use PicaJSON instead).

2021-12-15 10:51 UTC, nichtich commented
I've modified the description of JSON command and included a not on how to get PICA JSON, if needed.

2021-12-15 11:15 UTC, niko2342 approved these changes

2021-12-15 11:15 UTC, merged

2021-12-15 11:16 UTC, niko2342 commented
Thanks for your PR! Excellent idea to add the `jq`-code for converting between the different formats!