Extend documentation of print command (#513)
deutsche-nationalbibliothek/pica-rs pull request #571
Opened 2023-01-17 09:56 UTC by nichtich

Options --color and --add-spaces are mentioned. Other options (--limit, --translit...) are also available for other commands so they should better be documented elsewhere.

2023-01-17 11:52 UTC, niko2342 requested changes

2023-01-17 11:52 UTC, niko2342 commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
To be honest, I'm not sure if it's a good idea to emphasize the PICA Plain format. The `print` command prints a record on the terminal and it's not a data conversion tool. The fact, that the default output is PICA Plain, is a positive side effect; but I dont want to commit on PICA Plain, to be open for further improvements regarding readability. For example, I'm considering to make the `--add-spaces` option on by default, because the output is more readable.

2023-01-17 11:52 UTC, niko2342 commented on README.md
> -[PICA Plain](http://format.gbv.de/pica/plain) format.
Same here, i'd rather not mention PICA Plain. The format explanation looks fine.

2023-01-17 11:52 UTC, niko2342 commented on src/bin/pica/main.rs
> +    /// Print records in human readable PICA Plain format
Same here, i'd rather not mention PICA Plain.

2023-01-17 18:27 UTC, niko2342 commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
Can you explain you point a little bit more? What's the advantage to commit to the PICA Plain format? If this output format is import for you/others, we could add a new command, to write records in `PICA Plain`.

2023-01-18 12:09 UTC, nichtich commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
PICA Plain is used for human inspection of PICA+ data and copy & paste into tools such as [PicaEditor](https://pro4bib.github.io/pica/#/darstellung?id=codemirror) and to files. I also teach people not to invent their own formats every day but stick to something that is already being used. For PICA+ serialization we already have

- Normalized: best for machines (that's why standard in this tool)
- Plain: best for humans
- JSON and XML: if you happen to use JSON or XML data processing (but multiple variants exist for each)

If `print` is not going to emit strict PICA Plain format than how about a new command `plain` just like command `xml`?

2023-01-19 08:39 UTC, nichtich commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
See also issue https://github.com/deutsche-nationalbibliothek/pica-rs/issues/309.

2023-01-21 13:06 UTC, niko2342 commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
I think a new command would be the best solution (mid-term feature), or as an alternative, it could also a solution to add a new parameter `--plain` to output strict PICA Plain and disable option like `--color` or `--add-spaces`. I'm also fine with this alternative, because people already seems to use the `print` command for data format conversion.

What I'm still not understand: Where does the "**best** for humans" come from? I can't found references to papers or other resources, which did an usability investigation of the format. It's similar to programs like WinIBW and a librarian is familiar with this format, but this is not true e.g. a mathematician.

2023-01-23 07:44 UTC, nichtich commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
It's not the best per se, but best I found in existing tools, documents and conversation (I was already used when I started coding PICA processing tools around 15 years ago). Other and maybe more readable forms exist for sure! So two output forms may be helpful:

- pica plain output: for view and process (stable but not perfect)
- nice looking output: for view only (can be changed to user needs)

2023-01-23 12:38 UTC, niko2342 commented on README.md
> +| [print](#print)         | beta      | print records in human readable [PICA Plain](https://format.gbv.de/pica/plain) format |
A new `plain` command would be great!

2023-01-26 15:56 UTC, closed without merging