Extend documentation of filter command
deutsche-nationalbibliothek/pica-rs pull request #588
Opened 2023-01-31 17:23 UTC by nichtich

This should close #458.

2023-01-31 17:54 UTC, niko2342 requested changes
Thank you very much for the PR! 

I've found some minor things and I would like to invite you to add two more undocumented features (but this can also be done in a separate PR).

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +a query expression as filter criterion. The basic building block of query
As far as I know, the term "query expression" was never used before. Maybe we can switch to "query expression", but i would look to postpone the discussion unless the new matcher engine is completely introduced.

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +The dot (`.`) can be used as wildcard for any character in a field tag, so
This would be a good point to mention that it is also possible to name alternatives in each position, ex. `044[HK]` matches all tags which starts with `044` and ends with either `H` or `K`. Using alternatives in multiple positions, produces all combinations.

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +(`012A/00?`) or a subfield (`002@.0?`, `002@$0?`, `002@0?`, or `002@{0?}`)
Until now, the other variants (ex. lazy notation) are not documented yet. I don't like them, but I fully understand that might be a better variant for others and this should be documented. In order to keep the documentation consistent with one variant, I would prefer a separate paragraph on the different variants and keep the "dot"-notion dominant in the documentation.

Note: This is just a comment and not a blocker for this PR.

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +exists.  In order to test for the number of times of a field or subfield exists
~~of~~

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +(`#010@ == 1` or `010@{ #a == 1 && a == 'ger'}`).
Maybe it is also a good point to add a note that the cardinality operation accepts as comparison operator `==`, `!=`, `>=`, `>`, `<=`, and `<`.

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +connectives AND (`&&`) and OR (`||`). Boolean expressions are can be grouped
~~are~~

2023-01-31 17:54 UTC, niko2342 commented on README.md
> +equivalent to `A || (B && C)`. Expressions and evaluated lazy from left to
and -> are

2023-02-01 06:48 UTC, nichtich commented on README.md
> +a query expression as filter criterion. The basic building block of query
Right, I use a more generic "expression" so far. More precise name could be "filter expression" but to be decided together with wording of this expression-things in select and lint.

2023-02-01 07:44 UTC, nichtich commented on README.md
> +(`012A/00?`) or a subfield (`002@.0?`, `002@$0?`, `002@0?`, or `002@{0?}`)
I've omitted `002@0?` (should not be encouraged) and `002@{0?}` (possible but more complex and `{`...`}` might better be documented elsewhere).

2023-02-01 08:42 UTC, niko2342 approved these changes

2023-02-01 08:43 UTC, merged

2023-02-01 08:43 UTC, niko2342 commented
Looks fine, thanks for your contribution!