docs(book): Restore RMarkdown tutorial
deutsche-nationalbibliothek/pica-rs pull request #883
Opened 2024-12-10 05:03 UTC by nwagner84

2024-12-12 07:19 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +wird. Datenabfrage mit `pica` und Datenanalyse mit `R` können so in einem
werden statt wird

2024-12-12 07:21 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +knitr::opts_chunk$set(echo = TRUE, message = FALSE, dev="jpeg", dpi = 300, fig.path = "plots/")
dev="jpeg" - Eine Stilfrage: Wenn alle anderen Argumente ein Leerzeichen vor und nach dem = haben, warum dieses nicht?

2024-12-12 07:21 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +muss das Feld `041A` mit [select]-Kommando ausgelesen werden. Sind mehrere
mit dem

2024-12-12 07:23 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +[select]-Kommando diese automatisch, d.h. in der Ausgabe
Tatsächlich muss auch nach d.h. ein Komma gesetzt werden, wenn danach ein ganzer Nebensatz folgt.

2024-12-12 07:25 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +$ pica select -s --no-empty-columns -H "idn_titel, idn_sw" "003@.0,041A/*.9" \
Funktioniert das wirklich mit "$" vorneweg?

2024-12-12 07:26 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +gewünscht ist. Das Einlesen der Date in R erfolgt über die üblichen
Daten

2024-12-12 07:31 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +card_d <- sw_per_title |>
Geht das nicht kürzer?:
card_d <- sw_per_title |> summarise(avg_count = mean(n_sw)

2024-12-12 07:33 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 1) +
Ich bin mir nicht ganz sicher, ob die ..count..-Notation inzwischen deprecated ist.

2024-12-12 07:33 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +  ylab("Anteil an allen GND-Entität") +
an allen GND-Entitäten

2024-12-12 07:33 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +Eine andere Visualisierungsform des gleichen Sachverhalts ist Folgende:
folgende

2024-12-12 07:34 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +    ggtitle("Long-Tail Darstellung")
Long-Tail-Darstellung

2024-12-12 07:37 UTC, mschumac commented on docs/book/tutorials/rmarkdown.qmd
> +Zunächst erzeugen wir mit folgender Pica-Abfrage von der Datei `TEST.dat.gz`
Präposition aus statt von?

2024-12-12 07:43 UTC, mschumac requested changes
siehe Inline-Kommentare

2024-12-12 21:05 UTC, nwagner84 commented on docs/book/tutorials/rmarkdown.qmd
> +$ pica select -s --no-empty-columns -H "idn_titel, idn_sw" "003@.0,041A/*.9" \
Das `$`-Zeichen soll den Eingabeprompt symbolisieren; ich habe aber jetzt schon mehrfach das Feedback bekommen, dass das nicht verständlich ist. Außerdem wird das Copy&Paste erschwert. Ich werde das in einem separaten PullRequest für alle Seiten ändern.

2024-12-12 21:06 UTC, nwagner84 commented on docs/book/tutorials/rmarkdown.qmd
> +card_d <- sw_per_title |>
@mfakaehler was meinst du?

2024-12-12 21:06 UTC, nwagner84 commented on docs/book/tutorials/rmarkdown.qmd
> +  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 1) +
@mfakaehler was meinst du?

2024-12-12 21:10 UTC, nwagner84 commented
Lieber @mschumac,

vielen Dank für deine Anmerkungen! Ich habe fast alles geändert; die Anmerkungen zum R-Code überlasse ich @mfakaehler.

2024-12-16 13:16 UTC, mfakaehler commented on docs/book/tutorials/rmarkdown.qmd
> +card_d <- sw_per_title |>
Ja, stimmt. Habe ich so umgesetzt wie von @mschumac vorgeschlagen.

2024-12-16 13:18 UTC, mfakaehler commented
Kann aus meiner Sicht so gemerged werden.

2024-12-16 13:20 UTC, mfakaehler approved these changes

2024-12-16 13:31 UTC, merged